# Generated by Django 6.1.1 on 2026-10-05 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_administrativa', '0002_periodoacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoEmprendedor',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'equipo_emprendedor',
            },
        ),
        migrations.CreateModel(
            name='EstudianteEmprendedor',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='gestion_emprendimiento_2.equipoemprendedor')),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativa.usuario')),
            ],
            options={
                'db_table': 'estudiante_emprendedor',
            },
        ),
        migrations.AddField(
            model_name='equipoemprendedor',
            name='estudiante_lider',
            field=models.OneToOneField(db_column='id_estudiante_lider', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_liderado', to='gestion_emprendimiento_2.estudianteemprendedor'),
        ),
    ]
