# Generated by Django 6.1.1 on 2026-10-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0002_periodoacademico'),
        ('gestion_emprendimiento_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstudianteEmprendedor',
            new_name='Estudiante',
        ),
    ]
