# Generated by Django 6.1.1 on 2026-10-06 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_convocatorias', '0005_alter_iniciativa_estado'),
        ('gestion_emprendimiento_2', '0002_rename_estudianteemprendedor_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoemprendedor',
            name='iniciativa',
            field=models.OneToOneField(blank=True, db_column='id_iniciativa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to='gestion_convocatorias.iniciativa'),
        ),
    ]
