services:
#  db:
#    image: mysql:8.4
#    container_name: ideacampus_db
#    restart: always
#    ports:
#     - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - db_data:/var/lib/mysql
#      - ./database/init.sql:/docker-entrypoint-initdb.d/1_init.sql
#      - ./database/seeds.sql:/docker-entrypoint-initdb.d/2_seeds.sql 

  backend:
    build: 
      context: ./backend
    container_name: ideacampus_backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      # Refleja el código local en el contenedor (Hot Reloading)
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: ideacampus_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      # Refleja el código local
      - ./frontend:/app
      # Ignora la carpeta node_modules local para usar la del contenedor de Linux
      - /app/node_modules

volumes:
  db_data: