# Generated by Django 6.1.1 on 2026-09-22 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('google_id', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='VariableCaracterizacion',
            fields=[
                ('id_variable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_dato', models.CharField(max_length=20)),
                ('opciones', models.CharField(blank=True, max_length=500, null=True)),
                ('obligatoria', models.BooleanField(default=False)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'variable_caracterizacion',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativa.permiso')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativa.rol')),
            ],
            options={
                'db_table': 'rol_permiso',
                'constraints': [models.UniqueConstraint(fields=('rol', 'permiso'), name='unique_rol_permiso')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativa.rol')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativa.usuario')),
            ],
            options={
                'db_table': 'usuario_rol',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol'), name='unique_usuario_rol')],
            },
        ),
    ]
