# Generated by Django 6.1.1 on 2026-10-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id_periodo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('semestre', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('es_vigente', models.BooleanField(default=False)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'periodo_academico',
                'ordering': ['-anio', '-semestre'],
            },
        ),
    ]
