# Generated by Django 5.2.17 on 2026-10-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0002_periodoacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolpermiso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
