# Generated by Django 5.2.17 on 2026-09-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id_convocatoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('requisitos_documentacion', models.CharField(blank=True, max_length=500, null=True)),
                ('criterios_evaluacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('estado', models.CharField(default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'convocatoria',
            },
        ),
    ]
