# Generated by Django 6.1.1 on 2026-10-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0002_periodoacademico'),
        ('gestion_convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='creador',
            field=models.ForeignKey(blank=True, db_column='id_creador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocatorias_creadas', to='gestion_administrativa.usuario'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='periodo',
            field=models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocatorias', to='gestion_administrativa.periodoacademico'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='criterios_evaluacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='requisitos_documentacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificacionConvocatoria',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('apertura', 'Apertura de Convocatoria'), ('cierre_proximo', 'Cierre Próximo de Convocatoria'), ('cerrada', 'Convocatoria Cerrada'), ('actualizacion', 'Actualización de Convocatoria')], default='apertura', max_length=30)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(db_column='id_convocatoria', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion_convocatorias.convocatoria')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_convocatoria', to='gestion_administrativa.usuario')),
            ],
            options={
                'db_table': 'notificacion_convocatoria',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
