# Generated by Django 5.2.17 on 2026-10-06 01:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0003_alter_rolpermiso_id_alter_usuariorol_id'),
        ('gestion_convocatorias', '0002_alter_convocatoria_options_convocatoria_creador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id_iniciativa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('origen_academico', models.CharField(choices=[('asignatura', 'Asignatura'), ('semillero', 'Semillero de Investigación'), ('proyecto_integrador', 'Proyecto Integrador'), ('practica', 'Práctica'), ('trabajo_grado', 'Trabajo de Grado')], max_length=50)),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='iniciativas/documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de validación'), ('validada', 'Validada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(db_column='id_convocatoria', on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas', to='gestion_convocatorias.convocatoria')),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas_registradas', to='gestion_administrativa.usuario')),
            ],
            options={
                'db_table': 'iniciativa',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
