# Generated by Django 5.2.17 on 2026-10-06 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0003_alter_rolpermiso_id_alter_usuariorol_id'),
        ('gestion_convocatorias', '0003_iniciativa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iniciativa',
            options={'ordering': ['-fecha_postulacion']},
        ),
        migrations.RenameField(
            model_name='iniciativa',
            old_name='fecha_creacion',
            new_name='fecha_postulacion',
        ),
        migrations.RemoveField(
            model_name='iniciativa',
            name='documento_adjunto',
        ),
        migrations.RemoveField(
            model_name='iniciativa',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='iniciativa',
            name='titulo',
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='detalle_origen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='etapa_actual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='nombre',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='sector_tecnologico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='tipo',
            field=models.CharField(choices=[('emprendimiento', 'Emprendimiento'), ('innovacion', 'Innovación')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', default='', on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas', to='gestion_administrativa.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='origen_academico',
            field=models.CharField(choices=[('asignatura', 'Asignatura'), ('proyecto_aula', 'Proyecto de Aula'), ('integrador', 'Proyecto Integrador'), ('semillero', 'Semillero de Investigación'), ('practica', 'Práctica Profesional'), ('trabajo_grado', 'Trabajo de Grado')], max_length=30),
        ),
        migrations.CreateModel(
            name='DocumentoPostulacion',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('archivo', models.FileField(db_column='url_archivo', upload_to='iniciativas/pdf/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('iniciativa', models.ForeignKey(db_column='id_iniciativa', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion_convocatorias.iniciativa')),
            ],
            options={
                'db_table': 'documento_postulacion',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
