# Generated by Django 6.1.1 on 2026-10-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_convocatorias', '0004_alter_iniciativa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
