# Generated by Django 6.1.1 on 2026-10-02 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_administrativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('nivel_academico', models.CharField(blank=True, choices=[('pregrado', 'Pregrado'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=30, null=True)),
                ('anios_experiencia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True)),
                ('enlace_perfil', models.URLField(blank=True, max_length=300)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('id_mentor', models.AutoField(primary_key=True, serialize=False)),
                ('area_especializacion', models.CharField(blank=True, max_length=150)),
                ('disponibilidad', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativa.usuario')),
            ],
            options={
                'db_table': 'mentor',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('nivel_academico', models.CharField(blank=True, choices=[('pregrado', 'Pregrado'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=30, null=True)),
                ('anios_experiencia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True)),
                ('enlace_perfil', models.URLField(blank=True, max_length=300)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('area_conocimiento', models.CharField(blank=True, max_length=150)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativa.usuario')),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
    ]
